version: '3.9'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    hostname: postgres
    container_name: calendar_postgres_container
    ports:
      - 5435:5432
    volumes:
      - calend_pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations/psql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - default

volumes:
  calend_pgdata: