version: '3.9'

services:
  postgres:
    image: postgres:14.8-alpine3.18
    hostname: postgres
    container_name: calendar_postgres_container
    ports:
      - 5435:5432
    volumes:
      - calend_pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations/psql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - default
  mongodb:
    image: mongo:6.0
    container_name: calendar_mongo_container
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - calend_mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
volumes:
  calend_pgdata:
  calend_mongodata: